import { useCallback, useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Bell, Plus, Package, Clock, Truck, CheckCircle } from "lucide-react";
const API="http://localhost:5000/api";
function Dashboard(){
 const navigate=useNavigate(); const email=localStorage.getItem("reflexUserEmail")||"retailer001@gmail.com";
 const [deliveries,setDeliveries]=useState([]); const [orders,setOrders]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 const load=useCallback(async()=>{try{setError("");const [dr,or]=await Promise.all([fetch(`${API}/deliveries?retailerEmail=${encodeURIComponent(email)}`),fetch(`${API}/orders`)]);const dd=await dr.json(),oo=await or.json();if(!dr.ok||!dd.success)throw new Error(dd.message||"Failed to load deliveries");setDeliveries(dd.deliveries||[]);setOrders((oo.orders||[]).filter(o=>o.status==="New"));}catch(e){setError(e.message||"Unable to load dashboard")}finally{setLoading(false)}},[email]);
 useEffect(()=>{load();const id=setInterval(load,5000);return()=>clearInterval(id)},[load]);
 const pending=deliveries.filter(d=>d.status==="Pending").length,progress=deliveries.filter(d=>["Assigned","Picked Up"].includes(d.status)).length,done=deliveries.filter(d=>d.status==="Delivered").length;
 return <main className="main-content"><header className="top-header"><div><h1>Dashboard</h1><p>Orders and delivery requests</p></div><div className="header-actions"><button className="notification-button" onClick={()=>navigate("/retailer/notifications")}><Bell size={20}/></button><div className="profile"><div className="avatar">R</div><div><strong>{email.split("@")[0]}</strong><span>Retailer</span></div></div></div></header>
 <section className="welcome-section"><div><h2>Good morning</h2><p>Review customer orders and track deliveries.</p></div><button className="primary-button" onClick={()=>navigate("/retailer/new-delivery")}><Plus size={18}/>New Delivery</button></section>
 <section className="stats-grid">{[[Package,"Deliveries",deliveries.length],[Clock,"Pending",pending],[Truck,"In Progress",progress],[CheckCircle,"Delivered",done]].map(([Icon,label,value])=><div className="stat-card" key={label}><div className="stat-icon"><Icon size={24}/></div><div><span>{label}</span><h3>{loading?"...":value}</h3></div></div>)}</section>
 {error&&<div className="form-error">{error}</div>}
 <section className="deliveries-section"><div className="section-header"><div><h2>Customer Orders</h2><p>Orders waiting to be turned into delivery requests.</p></div></div><div className="delivery-table">{orders.length===0?<div className="delivery-row"><span>{loading?"Loading orders...":"No new customer orders"}</span></div>:orders.slice(0,5).map(o=><div className="delivery-row" key={o.id}><span>{o.id}</span><span>{o.customerName}</span><span>{o.items.map(i=>`${i.productName} x${i.quantity}`).join(", ")}</span><span className="status pending">{o.status}</span><button className="details-button" onClick={()=>navigate("/retailer/new-delivery")}>Create Delivery</button></div>)}</div></section>
 <section className="deliveries-section"><div className="section-header"><div><h2>Recent Deliveries</h2><p>Track delivery requests after assignment.</p></div><button className="view-all-button" onClick={()=>navigate("/retailer/my-deliveries")}>View All</button></div><div className="delivery-table">{deliveries.slice(0,5).map(d=><div className="delivery-row" key={d.id}><span>{d.id}</span><span>{d.customerName}</span><span>{d.destination}</span><span className={`status ${d.status.toLowerCase().replace(" ","-")}`}>{d.status}</span><button className="details-button" onClick={()=>navigate(`/retailer/delivery/${d.id}`,{state:{delivery:d}})}>View</button></div>)}</div></section>
 </main>;
}
export default Dashboard;
